version: '3.3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx-jwt
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - JWT_PUBLIC_KEY_FILE=/run/secrets/jwt-public
    secrets:
      - jwt-public
    volumes:
      - ./fast-api-jwt/fast-api-jwt.location:/etc/nginx/conf.d/locations/fast-api-jwt.location
      - ./nginx-jwt/conf/conf.d/default.conf/:/etc/nginx/conf.d/default.conf
      - certs:/etc/nginx/certs/

    depends_on:
      - fast-api-jwt
      - jwt-certs
    networks:
      - backend

  fast-api-jwt:
    container_name: fast-api
    build:
      context: ./fast-api-jwt
      dockerfile: Dockerfile
    environment: 
      - JWT_PRIVATE_KEY_FILE=/run/secrets/jwt-private
    networks:
      - backend
    secrets:
      - jwt-private


    ports:
      - 8080:8080
    command: ["uvicorn", "src.main:app", "--host=0.0.0.0", "--port", "8080"]

volumes:
  pub:
  priv:


networks:
  backend:
    driver: bridge

secrets:
  jwt-private:
    file: ${PRIVATE_KEY_PATH}
  jwt-public:
    file: ${PUBLIC_KEY_PATH}


      
    